apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongopv.name }}
spec:
  capacity:
    storage: {{ .Values.mongopv.storage }}
  accessModes:
    - {{ .Values.mongopv.accessMode }}
  storageClassName: {{ .Values.mongopv.storageClassName }}
  hostPath:
    path: {{ .Values.mongopv.hostPath }}