apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongosecret.name }}
  namespace: {{ .Values.mongosecret.namespace }}
type: Opaque
data:
  username: {{ .Values.mongosecret.username | b64enc | quote }} # Base64 encoded value of "admin"
  password: {{ .Values.mongosecret.password | b64enc | quote }} # Base64 encoded value of "admin"