apiVersion: v1
kind: Secret                # Specifies the Kubernetes resource type as Secret
metadata:
  name: mongo-secret        # Name of the Secret, in this case, "mongo-secret"
  namespace: survey-app     # Specifies the namespace where the Secret resides
type: Opaque                # Specifies the type of Secret as Opaque, which means arbitrary data
data:
  username: YWRtaW4=        # Base64 encoded value of "admin" for the username field
  password: YWRtaW4=        # Base64 encoded value of "admin" for the password field