apiVersion: "v1"
kind: "PersistentVolumeClaim"  # Specifies the Kubernetes resource type as PersistentVolumeClaim
metadata:
  name: "mongodb-pvc"           # Name of the PersistentVolumeClaim, in this case, "mongodb-pvc"
  namespace: "survey-app"       # Specifies the namespace where the PersistentVolumeClaim resides
  labels:                       # Labels attached to the PersistentVolumeClaim
    app: "mongo-db"             # Label indicating
spec:
  accessModes:                  # Specifies the access mode for the PersistentVolumeClaim
    - ReadWriteOnce             # Allows read/write access by a single node
  resources:        # Specifies the desired resources
    requests:
      storage: 1Gi              # Requests 1 gigabyte of storage
  storageClassName: gp2        # Specifies the storage class for dynamic provisioning